# Generated by Django 2.1.3 on 2018-12-06 20:32

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('champ_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('champ_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Match_Detail',
            fields=[
                ('match_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('match_data', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Match_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_list', django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None)),
                ('queue', models.CharField(max_length=10)),
                ('refresh', models.DateTimeField(verbose_name='last refreshed for this account and queue')),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Account')),
            ],
        ),
    ]
