# Generated by Django 2.1.3 on 2018-12-12 22:25

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match_list',
            name='account_id',
        ),
        migrations.AddField(
            model_name='account',
            name='flex_match_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
        migrations.AddField(
            model_name='account',
            name='refresh',
            field=models.DateTimeField(default=datetime.date(1, 1, 1), verbose_name='last refreshed for this account and queue'),
        ),
        migrations.AddField(
            model_name='account',
            name='solo_match_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), default=list, size=None),
        ),
        migrations.DeleteModel(
            name='Match_List',
        ),
    ]
