# Generated by Django 2.1.3 on 2018-12-15 20:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20181212_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='refresh',
            field=models.DateTimeField(default=datetime.date(1970, 1, 1), verbose_name='last refreshed for this account and queue'),
        ),
    ]
