# Generated by Django 2.1.3 on 2019-01-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_auto_20181215_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(max_length=64, primary_key=True, serialize=False),
        ),
    ]
