# Generated by Django 2.2.4 on 2020-03-20 03:49

import datetime
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0004_auto_20190101_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='refresh',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), verbose_name='last refreshed for this account and queue'),
        ),
        migrations.CreateModel(
            name='Aggregate_Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solo_champion_stats', django.contrib.postgres.fields.jsonb.JSONField()),
                ('flex_champion_stats', django.contrib.postgres.fields.jsonb.JSONField()),
                ('total_champion_stats', django.contrib.postgres.fields.jsonb.JSONField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytics.Account')),
            ],
        ),
    ]
