# Generated by Django 2.2.4 on 2020-03-30 05:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20200320_0349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match_Summary',
            fields=[
                ('match_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('match_summary', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
